# Generated by Django 5.0.7 on 2024-08-13 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('store_owner', 'store_owner'), ('customer', 'customer'), ('platform_admin', 'Platform Admin')], default='customer', max_length=20),
        ),
    ]
