# Generated by Django 5.0.7 on 2024-08-27 12:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_user_role'),
        ('stores', '0011_rename_domain_store_primary_domain_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StoreOwner',
        ),
    ]
