# Generated by Django 4.2.17 on 2024-12-22 13:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0002_customer_created_at_customer_updated_at_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MailingAddress',
            new_name='Address',
        ),
    ]
