# Generated by Django 5.0.7 on 2024-07-21 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='image',
            field=models.ImageField(default='assets/images/blog.jpg', upload_to='blog_posts/%y/%m/%d'),
        ),
    ]
