# Generated by Django 5.0.7 on 2024-07-22 11:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_post_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='image',
            field=models.ImageField(default='assets/images/blog.jpg', upload_to='blog_categories/%y/%m/%d'),
        ),
    ]
