# Generated by Django 5.0.7 on 2024-08-04 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0006_category_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(default='assets/images/blog.jpg', upload_to='blog/categories/%y/%m/%d'),
        ),
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='assets/images/blog.jpg', upload_to='blog/posts/%y/%m/%d'),
        ),
    ]
