# Generated by Django 5.1.4 on 2024-12-26 16:23

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0001_initial'),
        ('stores', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Archived', 'Archived'), ('Canceled', 'Canceled')], default='Open', max_length=32)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Authorized', 'Authorized'), ('Due', 'Due'), ('Expiring', 'Expiring'), ('Expired', 'Expired'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Partially refunded', 'Partially refunded'), ('Partially paid', 'Partially paid'), ('Voided', 'Voided'), ('Unpaid', 'Unpaid')], default='Pending', max_length=32)),
                ('fulfillment_status', models.CharField(choices=[('Fulfilled', 'Fulfilled'), ('Unfulfilled', 'Unfulfilled'), ('Partially fulfilled', 'Partially fulfilled'), ('Scheduled', 'Scheduled'), ('On hold', 'On hold')], default='Unfulfilled', max_length=32)),
                ('return_status', models.CharField(blank=True, choices=[('Return requested', 'Return requested'), ('Return in progress', 'Return in progress'), ('Returned', 'Returned'), ('Inspection complete', 'Inspection complete')], max_length=32, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('shipping_price_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), editable=False, max_digits=12)),
                ('shipping_price_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), editable=False, max_digits=12)),
                ('base_shipping_price_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_base_shipping_price_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_total_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_total_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_charged_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_authorized_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('subtotal_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('subtotal_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('display_gross_prices', models.BooleanField(default=True)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('billing_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.address')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customer.customer')),
                ('shipping_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.address')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_title', models.CharField(max_length=255)),
                ('variant_title', models.CharField(blank=True, default='', max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('is_shipping_required', models.BooleanField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_fulfilled', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('unit_discount_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('unit_price_net_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_discount_value', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('unit_price_gross_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_price_net_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_price_gross_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('undiscounted_unit_price_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_unit_price_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_total_price_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_total_price_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('base_unit_price_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_base_unit_price_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.order')),
            ],
        ),
    ]
