# Generated by Django 4.2.17 on 2024-12-22 19:29

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customer', '0003_rename_mailingaddress_address'),
        ('stores', '0022_store_currency_code_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Order',
            fields=[
                ('external_reference', models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True, db_index=True)),
                ('status', models.CharField(choices=[('Open', 'Open'), ('Archived', 'Archived'), ('Canceled', 'Canceled')], default='Open', max_length=32)),
                ('payment_status', models.CharField(choices=[('Pending', 'Pending'), ('Authorized', 'Authorized'), ('Due', 'Due'), ('Expiring', 'Expiring'), ('Expired', 'Expired'), ('Paid', 'Paid'), ('Refunded', 'Refunded'), ('Partially refunded', 'Partially refunded'), ('Partially paid', 'Partially paid'), ('Voided', 'Voided'), ('Unpaid', 'Unpaid')], default='Pending', max_length=32)),
                ('fulfillment_status', models.CharField(choices=[('Fulfilled', 'Fulfilled'), ('Unfulfilled', 'Unfulfilled'), ('Partially fulfilled', 'Partially fulfilled'), ('Scheduled', 'Scheduled'), ('On hold', 'On hold')], default='Unfulfilled', max_length=32)),
                ('return_status', models.CharField(blank=True, choices=[('Return requested', 'Return requested'), ('Return in progress', 'Return in progress'), ('Returned', 'Returned'), ('Inspection complete', 'Inspection complete')], max_length=32, null=True)),
                ('currency', models.CharField(max_length=3)),
                ('shipping_price_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), editable=False, max_digits=12)),
                ('shipping_price_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), editable=False, max_digits=12)),
                ('base_shipping_price_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_base_shipping_price_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_total_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_total_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_charged_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('total_authorized_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('subtotal_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('subtotal_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=12)),
                ('display_gross_prices', models.BooleanField(default=True)),
                ('customer_note', models.TextField(blank=True, default='')),
                ('billing_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.address')),
                ('customer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='customer.customer')),
                ('shipping_address', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer.address')),
                ('store', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='stores.store')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
