# Generated by Django 4.2.17 on 2024-12-25 00:23

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0034_alter_product_description'),
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderLine',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('product_title', models.CharField(max_length=255)),
                ('variant_title', models.CharField(blank=True, default='', max_length=255)),
                ('product_sku', models.CharField(blank=True, max_length=255, null=True)),
                ('is_shipping_required', models.BooleanField()),
                ('quantity', models.IntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('quantity_fulfilled', models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)])),
                ('currency', models.CharField(max_length=3)),
                ('unit_discount_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('unit_price_net_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('unit_discount_value', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('unit_price_gross_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_price_net_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('total_price_gross_amount', models.DecimalField(decimal_places=3, max_digits=12)),
                ('undiscounted_unit_price_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_unit_price_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_total_price_gross_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_total_price_net_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('base_unit_price_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('undiscounted_base_unit_price_amount', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('order', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='order.order')),
                ('variant', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order_lines', to='product.productvariant')),
            ],
        ),
    ]
