# Generated by Django 5.1.4 on 2025-03-09 02:22

import django.contrib.postgres.indexes
import django.db.models.deletion
import django.utils.timezone
import django_countries.fields
import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('order', '0003_order_canceled_at_order_completed_at_and_more'),
        ('product', '0001_initial'),
        ('stores', '0009_remove_staffmember_permissions_storepermission_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Voucher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('entire_order', 'Entire order'), ('shipping', 'Shipping'), ('specific_product', 'Specific products, collections and categories')], default='entire_order', max_length=20)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True)),
                ('start_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('end_date', models.DateTimeField(blank=True, null=True)),
                ('apply_once_per_order', models.BooleanField(default=False)),
                ('apply_once_per_customer', models.BooleanField(default=False)),
                ('single_use', models.BooleanField(default=False)),
                ('only_for_staff', models.BooleanField(default=False)),
                ('discount_value_type', models.CharField(choices=[('fixed', 'fixed'), ('percentage', '%')], default='fixed', max_length=10)),
                ('discount_value', models.DecimalField(decimal_places=3, max_digits=12)),
                ('min_spent_amount', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('countries', django_countries.fields.CountryField(blank=True, max_length=746, multiple=True)),
                ('min_checkout_items_quantity', models.PositiveIntegerField(blank=True, null=True)),
                ('collections', models.ManyToManyField(blank=True, to='product.collection')),
                ('products', models.ManyToManyField(blank=True, to='product.product')),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vouchers', to='stores.store')),
                ('variants', models.ManyToManyField(blank=True, to='product.productvariant')),
            ],
            options={
                'ordering': ('name', 'pk'),
            },
        ),
        migrations.CreateModel(
            name='OrderDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('voucher', 'Voucher'), ('manual', 'Manual')], default='manual', max_length=64)),
                ('value_type', models.CharField(choices=[('fixed', 'fixed'), ('percentage', '%')], default='fixed', max_length=10)),
                ('value', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('amount_value', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=255, null=True)),
                ('historical_currency', models.CharField(blank=True, max_length=3)),
                ('historical_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='order.order')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='discount.voucher')),
            ],
            options={
                'ordering': ('created_at',),
            },
        ),
        migrations.CreateModel(
            name='OrderLineDiscount',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('type', models.CharField(choices=[('sale', 'Sale'), ('voucher', 'Voucher'), ('manual', 'Manual')], default='manual', max_length=64)),
                ('value_type', models.CharField(choices=[('fixed', 'fixed'), ('percentage', '%')], default='fixed', max_length=10)),
                ('value', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('amount_value', models.DecimalField(decimal_places=3, default=Decimal('0.0'), max_digits=12)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('reason', models.TextField(blank=True, null=True)),
                ('voucher_code', models.CharField(blank=True, max_length=255, null=True)),
                ('historical_currency', models.CharField(blank=True, max_length=3)),
                ('historical_value', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('unique_type', models.CharField(blank=True, choices=[('sale', 'Sale'), ('voucher', 'Voucher'), ('manual', 'Manual')], max_length=64, null=True)),
                ('line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='discounts', to='order.orderline')),
                ('voucher', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='discount.voucher')),
            ],
            options={
                'ordering': ('created_at',),
                'constraints': [models.UniqueConstraint(fields=('line_id', 'unique_type'), name='unique_orderline_discount_type')],
            },
        ),
        migrations.CreateModel(
            name='VoucherCode',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, unique=True)),
                ('code', models.CharField(db_index=True, max_length=255, unique=True)),
                ('used', models.PositiveIntegerField(default=0)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('voucher', models.ForeignKey(db_index=False, on_delete=django.db.models.deletion.CASCADE, related_name='codes', to='discount.voucher')),
            ],
            options={
                'ordering': ('-created_at', 'code'),
                'indexes': [django.contrib.postgres.indexes.BTreeIndex(fields=['voucher'], name='vouchercode_voucher_idx')],
            },
        ),
    ]
