# Generated by Django 5.0.7 on 2024-08-14 22:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_storeowner'),
        ('stores', '0002_remove_store_country_remove_store_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stores', to='accounts.storeowner'),
        ),
    ]
