# Generated by Django 5.0.7 on 2024-08-09 17:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0002_historicalstore'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='country',
        ),
        migrations.RemoveField(
            model_name='store',
            name='domain',
        ),
        migrations.AddField(
            model_name='store',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
        migrations.AlterField(
            model_name='store',
            name='name',
            field=models.CharField(default='My Store', max_length=255),
        ),
        migrations.DeleteModel(
            name='HistoricalStore',
        ),
    ]
