# Generated by Django 5.1.4 on 2024-12-26 21:35

import stores.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0003_alter_domain_host_alter_store_default_domain'),
    ]

    operations = [
        migrations.AlterField(
            model_name='domain',
            name='host',
            field=models.CharField(max_length=255, unique=True),
        ),
        migrations.AlterField(
            model_name='store',
            name='default_domain',
            field=models.CharField(default=stores.utils.generate_unique_subdomain, editable=False, max_length=255, unique=True),
        ),
    ]
