# Generated by Django 5.0.7 on 2024-08-24 05:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0004_remove_store_phone_shopaddress'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ShopAddress',
            new_name='StoreAddress',
        ),
    ]
