# Generated by Django 5.1.4 on 2024-12-26 21:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='primary_domain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.domain'),
        ),
    ]
