# Generated by Django 5.0.7 on 2024-08-24 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_rename_shopaddress_storeaddress'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaddress',
            name='company',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='storeaddress',
            name='country_code_v2',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
