# Generated by Django 5.0.7 on 2024-08-09 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0005_alter_store_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='description',
        ),
        migrations.AddField(
            model_name='store',
            name='domain',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True),
        ),
    ]
