# Generated by Django 5.0.7 on 2024-08-26 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0006_alter_storeaddress_company_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='domain',
            new_name='default_domain',
        ),
        migrations.RemoveField(
            model_name='storeaddress',
            name='store',
        ),
    ]
