# Generated by Django 5.1.4 on 2024-12-26 22:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_alter_store_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaddress',
            name='store',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='stores.store'),
        ),
    ]
