# Generated by Django 5.0.7 on 2024-08-26 06:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0007_rename_domain_store_default_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='billing_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to='stores.storeaddress'),
        ),
    ]
