# Generated by Django 5.0.7 on 2024-08-26 06:58

import django_countries.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0008_store_billing_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeaddress',
            name='country_code_v2',
            field=django_countries.fields.CountryField(blank=True, max_length=2, null=True),
        ),
    ]
