# Generated by Django 5.1.4 on 2025-01-11 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('stores', '0008_alter_storeaddress_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staffmember',
            name='permissions',
        ),
        migrations.CreateModel(
            name='StorePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Permission Name')),
                ('codename', models.CharField(max_length=100, verbose_name='Codename')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype', verbose_name='Content Type')),
            ],
            options={
                'verbose_name': 'Store Permission',
                'verbose_name_plural': 'Store Permissions',
                'unique_together': {('codename', 'content_type')},
            },
        ),
        migrations.AddField(
            model_name='staffmember',
            name='permissions',
            field=models.ManyToManyField(blank=True, related_name='staff_members', to='stores.storepermission'),
        ),
    ]
