# Generated by Django 5.0.7 on 2024-08-27 09:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_alter_storeaddress_country_code_v2'),
    ]

    operations = [
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.AlterField(
            model_name='store',
            name='billing_address',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='stores.storeaddress'),
        ),
        migrations.AddField(
            model_name='store',
            name='domain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='stores.domain'),
        ),
    ]
