# Generated by Django 5.1.4 on 2025-03-21 10:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0009_remove_staffmember_permissions_storepermission_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='primary_domain',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='stores.domain'),
        ),
    ]
