# Generated by Django 5.0.7 on 2024-08-27 12:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0010_domain_alter_store_billing_address_store_domain'),
    ]

    operations = [
        migrations.RenameField(
            model_name='store',
            old_name='domain',
            new_name='primary_domain',
        ),
        migrations.RemoveField(
            model_name='store',
            name='owner',
        ),
        migrations.CreateModel(
            name='StaffMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('locale', models.CharField(max_length=50)),
                ('account_access', models.CharField(max_length=100)),
                ('is_shop_owner', models.BooleanField()),
                ('name', models.CharField(max_length=255)),
                ('first_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('permissions', models.JSONField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_members', to='stores.store')),
            ],
        ),
    ]
