# Generated by Django 5.0.7 on 2024-08-27 12:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0011_rename_domain_store_primary_domain_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='owner',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='owned_store', to='stores.staffmember'),
            preserve_default=False,
        ),
    ]
