# Generated by Django 5.0.7 on 2024-08-27 12:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0012_store_owner'),
    ]

    operations = [
        migrations.RenameField(
            model_name='staffmember',
            old_name='is_shop_owner',
            new_name='is_store_owner',
        ),
    ]
