# Generated by Django 5.0.7 on 2024-08-27 13:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0015_alter_store_owner'),
    ]

    operations = [
        migrations.AlterField(
            model_name='store',
            name='billing_address',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to='stores.storeaddress'),
        ),
    ]
