# Generated by Django 5.0.7 on 2024-08-27 13:20

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0016_alter_store_billing_address'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='staffmember',
            options={'verbose_name_plural': 'Staff Members'},
        ),
        migrations.AlterUniqueTogether(
            name='staffmember',
            unique_together={('user', 'store')},
        ),
    ]
