# Generated by Django 5.0.7 on 2024-08-29 00:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0017_alter_staffmember_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='billing_address',
        ),
    ]
