# Generated by Django 5.0.7 on 2024-08-29 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0018_remove_store_billing_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeaddress',
            name='store',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.CASCADE, related_name='billing_address', to='stores.store'),
            preserve_default=False,
        ),
    ]
