# Generated by Django 5.0.7 on 2024-08-29 01:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0019_storeaddress_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='staffmember',
            name='account_access',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='first_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='is_store_owner',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='locale',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='staffmember',
            name='permissions',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
