# Generated by Django 5.0.7 on 2024-08-29 06:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0020_alter_staffmember_account_access_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storeaddress',
            old_name='country_code_v2',
            new_name='country',
        ),
    ]
