# Generated by Django 5.0.7 on 2024-09-01 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stores', '0021_rename_country_code_v2_storeaddress_country'),
    ]

    operations = [
        migrations.AddField(
            model_name='store',
            name='currency_code',
            field=models.CharField(blank=True, max_length=5, null=True),
        ),
        migrations.AddField(
            model_name='store',
            name='enabled_presentment_currencies',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
