# Generated by Django 5.0.7 on 2024-09-02 10:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='media_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DRAFT', 'Draft')], default='DRAFT', max_length=10),
        ),
    ]
