# Generated by Django 5.0.7 on 2024-09-02 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_media_count_alter_product_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
