# Generated by Django 5.0.7 on 2024-09-11 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_alter_product_store'),
        ('stores', '0022_store_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'ACTIVE'), ('DRAFT', 'DRAFT')], default='DRAFT', max_length=10),
        ),
        migrations.AlterUniqueTogether(
            name='product',
            unique_together={('handle', 'store')},
        ),
    ]
