# Generated by Django 5.0.7 on 2024-09-12 19:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seo'),
        ('product', '0005_alter_product_status_alter_product_unique_together'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seo',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='product', to='core.seo'),
        ),
    ]
