# Generated by Django 5.0.7 on 2024-09-13 20:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0006_product_seo'),
        ('stores', '0022_store_currency_code_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='media_count',
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='product_images/')),
                ('alt_text', models.CharField(blank=True, max_length=255, null=True)),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_images', to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(related_name='products', to='product.image'),
        ),
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('youtube_url', models.URLField()),
                ('store', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_videos', to='stores.store')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(related_name='products', to='product.video'),
        ),
    ]
