# Generated by Django 5.0.7 on 2024-09-28 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seo'),
        ('product', '0009_productoption_optionvalue_productvariant'),
        ('stores', '0022_store_currency_code_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='product',
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name='product',
            constraint=models.UniqueConstraint(fields=('store', 'handle'), name='unique_store_handle'),
        ),
    ]
