# Generated by Django 5.0.7 on 2024-09-28 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0011_alter_product_images_alter_product_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='images',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.image'),
        ),
        migrations.AlterField(
            model_name='product',
            name='videos',
            field=models.ManyToManyField(blank=True, related_name='products', to='product.video'),
        ),
    ]
