# Generated by Django 5.0.7 on 2024-09-28 01:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0012_alter_product_images_alter_product_videos'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='option_values',
            field=models.ManyToManyField(blank=True, related_name='variants', to='product.optionvalue'),
        ),
    ]
