# Generated by Django 5.0.7 on 2024-09-28 02:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0013_alter_productvariant_option_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 28, 2, 6, 27, 502924, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
