# Generated by Django 5.0.7 on 2024-09-28 02:07

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0014_productvariant_created_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 9, 28, 2, 7, 12, 622755, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
