# Generated by Django 5.0.7 on 2024-09-28 02:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0015_alter_image_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
