# Generated by Django 5.0.7 on 2024-11-13 16:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0018_alter_productvariant_compare_at_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='productvariant',
            old_name='option_values',
            new_name='selected_options',
        ),
    ]
