# Generated by Django 5.0.7 on 2024-11-14 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0019_rename_option_values_productvariant_selected_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productvariant',
            name='compare_at_price',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
    ]
