# Generated by Django 5.0.7 on 2024-11-17 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0020_alter_productvariant_compare_at_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='stock',
            field=models.PositiveIntegerField(default=0, help_text='Available stock'),
        ),
    ]
