# Generated by Django 5.0.7 on 2024-11-21 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_seo'),
        ('product', '0021_productvariant_stock'),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('handle', models.CharField(max_length=255, unique=True)),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='product.image')),
                ('seo', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='collection', to='core.seo')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='collections',
            field=models.ManyToManyField(related_name='products', to='product.collection'),
        ),
    ]
