# Generated by Django 5.0.7 on 2024-11-21 18:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0022_collection_product_collections'),
        ('stores', '0022_store_currency_code_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='store',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, related_name='collections', to='stores.store'),
            preserve_default=False,
        ),
    ]
