# Generated by Django 5.0.7 on 2024-11-21 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0023_collection_store'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='handle',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
