# Generated by Django 5.0.7 on 2024-11-21 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0024_alter_collection_handle'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
