# Generated by Django 5.0.7 on 2024-11-21 20:06

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0026_alter_product_collections'),
    ]

    operations = [
        migrations.AddField(
            model_name='collection',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2024, 11, 21, 20, 6, 35, 430424, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
    ]
