# Generated by Django 5.0.7 on 2024-12-20 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0029_remove_product_images_remove_product_videos_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='external_reference',
            field=models.CharField(blank=True, db_index=True, max_length=250, null=True, unique=True),
        ),
    ]
