# Generated by Django 5.0.7 on 2024-12-20 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0030_product_external_reference_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='sort_order',
            field=models.IntegerField(db_index=True, editable=False, null=True),
        ),
    ]
