# Generated by Django 4.2.17 on 2024-12-20 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0031_productvariant_sort_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='price',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='price_amount',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True),
        ),
    ]
