# Generated by Django 4.2.17 on 2024-12-23 17:22

import core.db.fields
import core.utils.editorjs
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0033_alter_productvariant_compare_at_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='description',
            field=core.db.fields.SanitizedJSONField(blank=True, null=True, sanitizer=core.utils.editorjs.clean_editor_js),
        ),
    ]
